// AUTO-GENERATED by ShaderVariantRegistry — do not edit directly
// Regenerated when new shader variants are registered

#import bevy_pbr::forward_io::VertexOutput
#import bevy_pbr::mesh_functions
#import bevy_pbr::forward_io::Vertex
#import bevy_pbr::view_transformations::position_world_to_clip

#if SHADER_VARIANT == 0
    #import "shaders/materials/dissolve.wgsl" as variant_mod
#else if SHADER_VARIANT == 1
    #import "shaders/materials/energy.wgsl" as variant_mod
#else if SHADER_VARIANT == 2
    #import "shaders/materials/water.wgsl" as variant_mod
#endif

struct DynMatData {
    shader_mode: u32,
    alpha_mode_flag: u32,
    _pad: vec2<u32>,
    param0: vec4<f32>,
    param1: vec4<f32>,
    param2: vec4<f32>,
    param3: vec4<f32>,
    param4: vec4<f32>,
    param5: vec4<f32>,
    param6: vec4<f32>,
    param7: vec4<f32>,
}

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> material: DynMatData;

@fragment
fn fragment(in: VertexOutput) -> @location(0) vec4<f32> {
    return variant_mod::fragment(in, material.param0, material.param1, material.param2, material.param3, material.param4, material.param5, material.param6, material.param7);
}

@vertex
fn vertex(vertex_in: Vertex) -> VertexOutput {
    var out: VertexOutput;
    let model = mesh_functions::get_world_from_local(vertex_in.instance_index);
    out.world_position = mesh_functions::mesh_position_local_to_world(model, vec4<f32>(vertex_in.position, 1.0));
    out.world_normal = mesh_functions::mesh_normal_local_to_world(vertex_in.normal, vertex_in.instance_index);
#ifdef VERTEX_UVS
    out.uv = vertex_in.uv;
#endif
#ifdef VERTEX_UVS_B
    out.uv_b = vertex_in.uv_b;
#endif
#ifdef VERTEX_TANGENTS
    out.world_tangent = mesh_functions::mesh_tangent_local_to_world(model, vertex_in.tangent, vertex_in.instance_index);
#endif
#ifdef VERTEX_COLORS
    out.color = vertex_in.color;
#endif
#ifdef HAS_VERTEX_SHADER
    let wpo = variant_mod::vertex(out.world_position.xyz, out.world_normal, material.param0, material.param1, material.param2, material.param3, material.param4, material.param5, material.param6, material.param7);
    out.world_position += vec4<f32>(wpo, 0.0);
#endif
    out.position = position_world_to_clip(out.world_position.xyz);
    return out;
}

